const actions = {
  GET_EXPENSES_REQUEST: 'GET_EXPENSES_REQUEST',
  GET_EXPENSES_FAIL: 'GET_EXPENSES_FAIL',
  GET_EXPENSES_SUCCESS: 'GET_EXPENSES_SUCCESS',
  SET_EXPENSES: 'SET_EXPENSES',

  CHANGE_PAGE_REQUEST: 'CHANGE_PAGE_REQUEST',
  CHANGE_PAGE_SUCCESS: 'CHANGE_PAGE_SUCCESS',
  SET_PAGE: 'SET_PAGE',
};

export default actions;
