const actions = {
  GET_EXPENSES_REQUEST: 'GET_EXPENSES_REQUEST',
  GET_EXPENSES_FAIL: 'GET_EXPENSES_FAIL',
  GET_EXPENSES_SUCCESS: 'GET_EXPENSES_SUCCESS',

  GET_PAGE_REQUEST: 'GET_PAGE_REQUEST',
};

export default actions;
