const actions = {
  GET_EXPENSES_REQUEST: 'GET_EXPENSES_REQUEST',
  GET_EXPENSES_FAIL: 'GET_EXPENSES_FAIL',
  GET_EXPENSES_SUCCESS: 'GET_EXPENSES_SUCCESS',

  CHANGE_PAGE_REQUEST: 'CHANGE_PAGE_REQUEST',
  CHANGE_PAGE_SUCCESS: 'CHANGE_PAGE_SUCCESS',
};

export default actions;
